### Common
server:
  port: 8030
  error:
    include-message: always

spring:
  application:
    name: personal-notebook
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/personal-notebook}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:psql12345678}

---
